/*
 MelonJS Game Engine
 Copyright (C) 2012, Olivier BIOT
 http://www.melonjs.org

 melonJS is licensed under the MIT License.
 http://www.opensource.org/licenses/mit-license.php

 Tween JS
 https://github.com/sole/Tween.js
*/
(function(a,c){function b(){if(!j){if(!d.body)return setTimeout(b,13);d.removeEventListener?d.removeEventListener("DOMContentLoaded",b,!1):a.removeEventListener("load",b,!1);j=!0;for(var f=0;f<h.length;f++)h[f].call(a,[]);h.length=0}}function e(){return{xmlDoc:null,parser:null,parseFromString:function(d){a.DOMParser?(this.parser=new DOMParser,this.xmlDoc=this.parser.parseFromString(d,"text/xml")):(this.xmlDoc=new ActiveXObject("Microsoft.XMLDOM"),this.xmlDoc.async="false",this.xmlDoc.loadXML(d));
null==this.xmlDoc&&console.log("xml "+this.xmlDoc+" not found!")},getFirstElementByTagName:function(a){return this.xmlDoc?this.xmlDoc.getElementsByTagName(a)[0]:null},getAllTagElements:function(){return this.xmlDoc?this.xmlDoc.getElementsByTagName("*"):null},getStringAttribute:function(a,d,b){return(a=a.getAttribute(d))?a.trim():b},getIntAttribute:function(a,d,b){return(a=this.getStringAttribute(a,d,b))?parseInt(a):b},getFloatAttribute:function(a,d,b){return(a=this.getStringAttribute(a,d,b))?parseFloat(a):
b},getBooleanAttribute:function(a,d,b){return(a=this.getStringAttribute(a,d,b))?"true"==a:b},free:function(){this.parser=this.xmlDoc=null}}}var d=a.document;me={mod:"melonJS",nocache:"",audio:null,video:null,timer:null,input:null,state:null,game:null,entityPool:null,levelDirector:null,XMLParser:null,loadingScreen:null,TMXTileMap:null,debug:{displayFPS:!1,renderHitBox:!1,renderDirty:!1}};me.sys={ua:navigator.userAgent.toLowerCase(),sound:!1,localStorage:"object"==typeof a.localStorage,gyro:a.DeviceMotionEvent!==
c,nativeBase64:"function"==typeof a.atob,touch:!1,fps:60,interpolation:!1,scale:1,gravity:c,useNativeAnimFrame:!1,cacheImage:!1,dirtyRegion:!1,enableWebGL:!1,stopOnAudioError:!0};a.me=me;var f=!1,g=!1,j=!1,h=[];onReady=function(f){g||(g=!0,"complete"===d.readyState?util.domReady():(d.addEventListener&&d.addEventListener("DOMContentLoaded",b,!1),a.addEventListener("load",b,!1)));j?f.call(a,[]):h.push(function(){return f.call(a,[])});return this};a.onReady(function(){if(!f){var b=d.createElement("audio");
me.utils.setNocache(d.location.href.match(/\?nocache/));if(b.canPlayType)me.audio.capabilities.mp3="no"!=b.canPlayType("audio/mpeg")&&""!=b.canPlayType("audio/mpeg"),me.audio.capabilities.ogg="no"!=b.canPlayType('audio/ogg; codecs="vorbis"')&&""!=b.canPlayType('audio/ogg; codecs="vorbis"'),me.audio.capabilities.wav="no"!=b.canPlayType('audio/wav; codecs="1"')&&""!=b.canPlayType('audio/wav; codecs="1"'),me.sys.sound=me.audio.capabilities.mp3||me.audio.capabilities.ogg||me.audio.capabilities.wav;if(-1<
me.sys.ua.search("iphone")||-1<me.sys.ua.search("ipod")||-1<me.sys.ua.search("ipad")||-1<me.sys.ua.search("android"))me.sys.sound=!1;me.sys.touch="createTouch"in d||"ontouchstart"in a;me.timer.init();me.XMLParser=new e;me.loadingScreen=new me.DefaultLoadingScreen;me.state.init();me.entityPool.init();me.levelDirector.reset();f=!0}});var k=!1,l=/xyz/.test(function(){})?/\bparent\b/:/.*/;Object.extend=function(a){function d(){!k&&this.init&&this.init.apply(this,arguments)}var b=this.prototype;k=!0;var f=
new this;k=!1;for(var g in a)f[g]="function"==typeof a[g]&&"function"==typeof b[g]&&l.test(a[g])?function(a,d){return function(){var f=this.parent;this.parent=b[a];var g=d.apply(this,arguments);this.parent=f;return g}}(g,a[g]):a[g];d.prototype=f;d.constructor=d;d.extend=arguments.callee;return d};if("function"!==typeof Object.create)Object.create=function(a){function d(){}d.prototype=a;return new d};if(!Function.bind)Function.prototype.bind=function(){var a=this,d=Array.prototype.slice.call(arguments),
b=d.shift();return function(){return a.apply(b,d.concat(Array.prototype.slice.call(arguments)))}};"undefined"===typeof console&&(console={log:function(){}});Function.prototype.defer=function(){var a=this,d=Array.prototype.slice.call(arguments);return window.setTimeout(function(){return a.apply(a,d)},0.01)};if(!Object.defineProperty)Object.defineProperty=function(a,d,b){if(a.__defineGetter__)b.get&&a.__defineGetter__(d,b.get),b.set&&a.__defineSetter__(d,b.set);else throw"melonJS: Object.defineProperty not supported";
};String.prototype.trim=function(){return this.replace(/^\s+/,"").replace(/\s+$/,"")};String.prototype.isNumeric=function(){return null!=this&&!isNaN(this)&&""!=this.trim()};String.prototype.isBoolean=function(){return null!=this&&("true"==this.trim()||"false"==this.trim())};String.prototype.contains=function(a){return-1<this.indexOf(a)};String.prototype.toHex=function(){for(var a="",d=0;d<this.length;)a+=this.charCodeAt(d++).toString(16);return a};Number.prototype.clamp=function(a,d){return this<
a?a:this>d?d:this};Number.prototype.random=function(a,d){return~~(Math.random()*(d-a+1))+a};Number.prototype.round=function(){var a=1==arguments.length?this:arguments[0],d=Math.pow(10,arguments[1]||arguments[0]);return Math.round(a*d)/d};Number.prototype.toHex=function(){return"0123456789ABCDEF".charAt(this-this%16>>4)+"0123456789ABCDEF".charAt(this%16)};Number.prototype.sign=function(){return 0>this?-1:0<this?1:0};Number.prototype.degToRad=function(a){return(a||this)/180*Math.PI};Number.prototype.radToDeg=
function(a){return(a||this)*(180/Math.PI)};var i=function(){var a={},d=[],b,f=[];a.isDirty=!1;a.reset=function(){d.length=0;f.length=0;b=me.game.viewport.getRect();a.makeAllDirty()};a.makeDirty=function(b,g,c){if(g)a.isDirty=!0,me.sys.dirtyRegion&&(c?d.push(c.union(b)):b.getRect&&d.push(b.getRect()));b.visible&&f.splice(0,0,b)};a.makeAllDirty=function(){d.length=0;d.push(b);a.isDirty=!0};a.remove=function(d){f.splice(f.indexOf(d),1);var b=d.visible;d.visible=!1;a.makeDirty(d,!0);d.visible=b};a.draw=
function(a){for(var b=d.length,g;b--,g=d[b];){for(var c=f.length,e;c--,e=f[c];)(!me.sys.dirtyRegion||!e.isEntity||e.overlaps(g))&&e.draw(a,g);me.debug.renderDirty&&g.draw(a,"white")}};a.flush=function(){if(me.sys.dirtyRegion)d.length=0;f.length=0;a.isDirty=!1};return a}();me.game=function(){var a={},d=null,b=[],f=0,g=!1,c=null;a.viewport=null;a.HUD=null;a.collisionMap=null;a.currentLevel=null;a.NO_OBJECT=0;a.ENEMY_OBJECT=1;a.COLLECTABLE_OBJECT=2;a.ACTION_OBJECT=3;a.onLevelLoaded=null;a.init=function(b,
f){if(!g)b=b||me.video.getWidth(),f=f||me.video.getHeight(),a.viewport=new me.Viewport(0,0,b,f),d=me.video.getScreenFrameBuffer(),g=!0};a.reset=function(){c&&clearTimeout(c);c=null;g||a.init();a.removeAll();a.viewport&&a.viewport.reset();null!=a.HUD&&a.add(a.HUD);i.reset()};a.loadTMXLevel=function(d){a.currentLevel=d;a.collisionMap=a.currentLevel.getLayerByName("collision");(!a.collisionMap||!a.collisionMap.isCollisionMap)&&alert("WARNING : no collision map detected");a.currentLevel.addTo(me.game);
if(a.currentLevel.realwidth<a.viewport.getWidth()||a.currentLevel.realheight<a.viewport.getHeight())throw"melonJS: map size should be at least equal to the defined display size";a.viewport.setBounds(a.currentLevel.realwidth,a.currentLevel.realheight);for(var b=a.currentLevel.getObjectGroups(),f=0;f<b.length;f++)for(var g=0;g<b[f].objects.length;g++)a.addEntity(b[f].objects[g],b[f].z);a.sort();a.onLevelLoaded&&a.onLevelLoaded.apply(a.onLevelLoaded,Array(d.name))};a.add=function(a,d){a.z=d?d:a.z;b.push(a);
f=b.length};a.addEntity=function(d,b){a.add(me.entityPool.newIstanceOf(d),b)};a.getEntityByName=function(a){for(var d=[],a=a.toLowerCase(),g=f,c;g--,c=b[g];)c.name==a&&d.push(c);return d};a.getEntityByGUID=function(a){for(var d=f,g;d--,g=b[d];)if(g.isEntity&&g.GUID==a)return g;return null};a.addHUD=function(d,b,f,g,c){if(null==a.HUD)a.HUD=new me.HUD_Object(d,b,f,g,c),a.add(a.HUD)};a.disableHUD=function(){if(null!=a.HUD)a.remove(a.HUD),a.HUD=null};a.update=function(){me.timer.update();for(var d=null,
g=f,c;g--,c=b[g];){var d=me.sys.dirtyRegion&&c.isEntity?c.getRect():null,e=c.update();if(c.isEntity)c.visible=a.viewport.isVisible(c.collisionBox);i.makeDirty(c,e,e?d:null)}a.viewport.update(i.isDirty)&&i.makeAllDirty()};a.remove=function(a){if(!a.destroy||a.destroy())a.visible=!1,a.isEntity=!1,i.remove(a),c=function(a){a=b.indexOf(a);if(-1!=a)b.splice(a,1),f=b.length;c=null}.defer(a)};a.removeAll=function(){for(var a=f,d;a--,d=b[a];)d.autodestroy=!0,d.destroy&&d.destroy();f=0;b.length=0;i.flush()};
a.sort=function(){b.sort(function(a,d){return d.z-a.z});a.repaint()};a.collide=function(a){for(var d=null,g=f,c;(g--,c=b[g])&&(!(c.visible&&c.collidable&&c.isEntity&&c!=a)||!(d=c.checkCollision(a))););return d};a.repaint=function(){i.makeAllDirty()};a.draw=function(){i.isDirty&&(i.draw(d),a.viewport.draw(d));i.flush()};return a}();me.ScreenObject=Object.extend({visible:!0,addAsObject:!1,rect:null,init:function(a){this.addAsObject=a;this.visible=!0===a||!1;this.rect=new me.Rect(new me.Vector2d(0,0),
0,0)},reset:function(){me.game.reset();if(this.addAsObject)this.visible=!0,this.rect=me.game.viewport.getRect(),me.game.add(this,999);this.onResetEvent.apply(this,arguments);me.game.sort()},getRect:function(){return this.rect},destroy:function(){this.onDestroyEvent.apply(this,arguments);return!0},update:function(){return!1},onUpdateFrame:function(){me.game.update();me.game.draw();me.video.blitSurface()},draw:function(){},onResetEvent:function(){},onDestroyEvent:function(){}});window.requestAnimFrame=
function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(){return-1}}();window.cancelRequestAnimFrame=function(){return window.cancelAnimationFrame||window.webkitCancelRequestAnimationFrame||window.mozCancelRequestAnimationFrame||window.oCancelRequestAnimationFrame||window.msCancelRequestAnimationFrame||function(){return-1}}();me.state=function(){function d(){if(-1==
j&&-1==h){me.timer.reset();if(me.sys.useNativeAnimFrame){h=window.requestAnimFrame(b);if(-1!=h)return;me.sys.useNativeAnimFrame=!1}j=setInterval(t,x)}}function b(){t();window.requestAnimFrame(b)}function f(){-1!=j&&(clearInterval(j),j=-1);-1!=h&&(cancelRequestAnimFrame(h),h=-1)}function g(a){f();i[e]&&(i[e].screen.visible?me.game.remove(i[e].screen):i[e].screen.destroy());i[a]&&(e=a,i[e].screen.reset.apply(i[e].screen,u),t=i[e].screen.onUpdateFrame.bind(i[e].screen),d(),v&&v(),me.game.repaint())}
var c={},e=-1,j=-1,h=-1,i={},l="",k=0,v=null,u=null,t=null,x=null;c.LOADING=0;c.MENU=1;c.READY=2;c.PLAY=3;c.GAMEOVER=4;c.GAME_END=5;c.SCORE=6;c.CREDITS=7;c.SETTINGS=8;c.onPause=null;c.onResume=null;c.init=function(){c.set(c.LOADING,me.loadingScreen);a.addEventListener("blur",function(){if(e!=c.LOADING&&(c.pause(!0),c.onPause))c.onPause()},!1);a.addEventListener("focus",function(){if(e!=c.LOADING){c.resume(!0);if(c.onResume)c.onResume();me.game.repaint()}},!1);x=~~(1E3/me.sys.fps)};c.pause=function(a){f();
a&&me.audio.pauseTrack()};c.resume=function(a){d(e);a&&me.audio.resumeTrack()};c.isRunning=function(){return-1!=j||-1!=h};c.set=function(a,d){i[a]={};i[a].screen=d;i[a].transition=!0};c.current=function(){return i[e].screen};c.transition=function(a,d,b){"fade"==a&&(l=d,k=b)};c.setTransition=function(a,d){i[a].transition=d};c.change=function(a){switch(a){default:u=null,1<arguments.length&&(u=Array.prototype.slice.call(arguments,1)),k&&i[a].transition?(v=function(){me.game.viewport.fadeOut(l,k)},me.game.viewport.fadeIn(l,
k,function(){g(a)})):g.defer(a)}};c.isCurrent=function(a){return e==a};return c}()})(window);
(function(a,c){me.DefaultLoadingScreen=me.ScreenObject.extend({init:function(){this.parent(!0);this.logo1=new me.Font("century gothic",32,"white");this.logo2=new me.Font("century gothic",32,"#89b002");this.logo2.bold();this.invalidate=!1;this.loadPercent=0;me.loader.onProgress=this.onProgressUpdate.bind(this)},onDestroyEvent:function(){this.logo1=this.logo2=null},onProgressUpdate:function(a){this.loadPercent=a;this.invalidate=!0},update:function(){return!0===this.invalidate?(this.invalidate=!1,!0):
!1},draw:function(a){var c=a.canvas.height/2,d=this.logo1.measureText(a,"melon").width,f=d+this.logo2.measureText(a,"JS").width;me.video.clearSurface(a,"black");this.logo1.draw(a,"melon",(a.canvas.width-f)/2,(a.canvas.height+60)/2);this.logo2.draw(a,"JS",(a.canvas.width-f)/2+d,(a.canvas.height+60)/2);c+=40;d=Math.floor(this.loadPercent*a.canvas.width);a.strokeStyle="silver";a.strokeRect(0,c,a.canvas.width,6);a.fillStyle="#89b002";a.fillRect(2,c+2,d-4,2)}});me.loader=function(){function b(){if(l==
k-i){for(var a in j)j[a].isTMX&&(me.levelDirector.addTMXLevel(a),f.onResourceLoaded());f.onload?setTimeout(f.onload,300):alert("no load callback defined")}else setTimeout(b,100)}function e(d,b,f,c){if(a.XMLHttpRequest){var g=new XMLHttpRequest;g.overrideMimeType&&g.overrideMimeType("text/xml")}else g=new ActiveXObject("Microsoft.XMLHTTP");g.open("GET",d.src+me.nocache,!1);g.onerror=c;g.onload=function(){j[d.name]={};j[d.name].xml=g.responseText;j[d.name].isTMX=b;f()};b&&(this.resourceCount+=1,this.tmxCount+=
1);g.send()}function d(a,d,b){var f=new XMLHttpRequest;f.open("GET",a.src+me.nocache,!1);f.responseType="arraybuffer";xmlhttp.onerror=b;f.onload=function(){var b=f.response;if(b){var b=new Uint8Array(b),g=[];h[a.name]=new dataType;for(var c=0;c<b.byteLength;c++)g[c]=String.fromCharCode(b[c]);h[a.name].data=g.join("");d()}};f.send()}var f={},g=[],j={},h={},k=0,l=0,i=0;f.onload=c;f.onProgress=c;f.onResourceLoaded=function(){l++;if(f.onProgress)f.onProgress(f.getLoadProgress())};f.onLoadingError=function(a){throw"melonJS: Failed loading resource "+
a.src;};f.preload=function(a){for(var d=0;d<a.length;d++)k+=f.load(a[d],f.onResourceLoaded.bind(f),f.onLoadingError.bind(f,a[d]));b()};f.load=function(a,b,f){a.name=a.name.toLowerCase();switch(a.type){case "binary":return d(a,b,f),1;case "image":return g.push(a.name),g[a.name]=new Image,g[a.name].onload=b,g[a.name].onerror=f,g[a.name].src=a.src+me.nocache,1;case "tmx":return e(a,!0,b,f),1;case "audio":me.audio.setLoadCallback(b);if(me.audio.isAudioEnable())return me.audio.load(a),1;break;default:throw"melonJS: me.loader.load : unknow or invalide resource type : %s"+
a.type;}return 0};f.getXML=function(a){a=a.toLowerCase();return null!=j?j[a].xml:null};f.getBinary=function(a){a=a.toLowerCase();return null!=h?h[a]:null};f.getImage=function(a){a=a.toLowerCase();if(null!=g[a]){if(!0===me.sys.cacheImage){var d=me.video.createCanvasSurface(g[a].width,g[a].height);d.drawImage(g[a],0,0);return d.canvas}return g[a]}return null};f.getLoadProgress=function(){return l/k};return f}()})(window);
(function(){me.Vector2d=Object.extend({x:0,y:0,init:function(a,c){this.x=a||0;this.y=c||0},set:function(a,c){this.x=a;this.y=c},setZero:function(){this.set(0,0)},setV:function(a){this.x=a.x;this.y=a.y},add:function(a){this.x+=a.x;this.y+=a.y},sub:function(a){this.x-=a.x;this.y-=a.y},scale:function(a){this.x*=a.x;this.y*=a.y},div:function(a){this.x/=a;this.y/=a},abs:function(){if(0>this.x)this.x=-this.x;if(0>this.y)this.y=-this.y},clamp:function(a,c){return new me.Vector2d(this.x.clamp(a,c),this.y.clamp(a,
c))},minV:function(a){this.x=this.x<a.x?this.x:a.x;this.y=this.y<a.y?this.y:a.y},maxV:function(a){this.x=this.x>a.x?this.x:a.x;this.y=this.y>a.y?this.y:a.y},floor:function(){return new me.Vector2d(~~this.x,~~this.y)},ceil:function(){return new me.Vector2d(Math.ceil(this.x),Math.ceil(this.y))},negate:function(){return new me.Vector2d(-this.x,-this.y)},negateSelf:function(){this.x=-this.x;this.y=-this.y},copy:function(a){this.x=a.x;this.y=a.y},length:function(){return Math.sqrt(this.x*this.x+this.y*
this.y)},normalize:function(){var a=this.length();if(a<Number.MIN_VALUE)return 0;var c=1/a;this.x*=c;this.y*=c;return a},dotProduct:function(a){return this.x*a.x+this.y*a.y},distance:function(a){return Math.sqrt((this.x-a.x)*(this.x-a.x)+(this.y-a.y)*(this.y-a.y))},clone:function(){return new me.Vector2d(this.x,this.y)},toString:function(){return"x:"+this.x+"y:"+this.y}});me.Rect=Object.extend({pos:null,colPos:null,left:null,right:null,top:null,bottom:null,width:0,height:0,hWidth:0,hHeight:0,hProp:!1,
vProp:!1,init:function(a,c,b){this.pos=a;this.colPos=new me.Vector2d;this.width=c;this.height=b;this.hWidth=~~(c/2);this.hHeight=~~(b/2);Object.defineProperty(this,"left",{get:function(){return this.pos.x},configurable:!0});Object.defineProperty(this,"right",{get:function(){return this.pos.x+this.width},configurable:!0});Object.defineProperty(this,"top",{get:function(){return this.pos.y},configurable:!0});Object.defineProperty(this,"bottom",{get:function(){return this.pos.y+this.height},configurable:!0})},
set:function(a,c,b){this.pos=a;this.width=c;this.height=b;this.hWidth=~~(c/2);this.hHeight=~~(b/2)},getRect:function(){return new me.Rect(this.pos.clone(),this.width,this.height)},union:function(a){var c=Math.min(this.pos.x,a.pos.x),b=Math.min(this.pos.y,a.pos.y);this.width=Math.ceil(Math.max(this.pos.x+this.width,a.pos.x+a.width)-c);this.height=Math.ceil(Math.max(this.pos.y+this.height,a.pos.y+a.height)-b);this.pos.x=~~c;this.pos.y=~~b;return this},adjustSize:function(a,c,b,e){if(-1!=a&&(this.colPos.x=
a,this.width=c,this.hWidth=~~(this.width/2),!this.hProp))Object.defineProperty(this,"left",{get:function(){return this.pos.x+this.colPos.x},configurable:!0}),Object.defineProperty(this,"right",{get:function(){return this.pos.x+this.colPos.x+this.width},configurable:!0}),this.hProp=!0;if(-1!=b&&(this.colPos.y=b,this.height=e,this.hHeight=~~(this.height/2),!this.vProp))Object.defineProperty(this,"top",{get:function(){return this.pos.y+this.colPos.y},configurable:!0}),Object.defineProperty(this,"bottom",
{get:function(){return this.pos.y+this.colPos.y+this.height},configurable:!0}),this.vProp=!0},flipX:function(a){this.colPos.x=a-this.width-this.colPos.x;this.hWidth=~~(this.width/2)},flipY:function(a){this.colPos.y=a-this.height-this.colPos.y;this.hHeight=~~(this.height/2)},overlaps:function(a){return this.left<a.right&&a.left<this.right&&this.top<a.bottom&&a.top<this.bottom},within:function(a){return a.left<=this.left&&a.right>=this.right&&a.top<=this.top&&a.bottom>=this.bottom},contains:function(a){return a.left>=
this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom},containsPoint:function(a){return a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom},collideVsAABB:function(a){var c=new me.Vector2d(0,0);if(this.overlaps(a)){var b=this.left+this.hWidth-a.left-a.hWidth,e=this.top+this.hHeight-a.top-a.hHeight;c.x=a.hWidth+this.hWidth-(0>b?-b:b);c.y=a.hHeight+this.hHeight-(0>e?-e:e);c.x<c.y?(c.y=0,c.x=0>b?-c.x:c.x):(c.x=0,c.y=0>e?-c.y:c.y)}return c},draw:function(a,c){a.strokeStyle=
c||"red";a.strokeRect(this.left-me.game.viewport.pos.x,this.top-me.game.viewport.pos.y,this.width,this.height)}})})(window);
(function(){var a=Math.min,c=Math.max;me.Viewport=me.Rect.extend({AXIS:{NONE:0,HORIZONTAL:1,VERTICAL:2,BOTH:3},limits:null,target:null,follow_axis:0,_shake:null,_fadeIn:null,_fadeOut:null,_deadwidth:0,_deadheight:0,_limitwidth:0,_limitheight:0,init:function(a,c,d,f,g,j){this.parent(new me.Vector2d(a,c),d-a,f-c);this.last=new me.Vector2d(-1,-1);this.limits=new me.Vector2d(g||this.width,j||this.height);this.target=null;this.follow_axis=this.AXIS.NONE;this._shake={intensity:0,duration:0,axis:this.AXIS.BOTH,
onComplete:null};this._fadeOut={color:0,alpha:0,duration:0,tween:null};this._fadeIn={color:0,alpha:1,duration:0,tween:null};this.setDeadzone(this.width/6,this.height/6)},_followH:function(b){if(b.x-this.pos.x>this._deadwidth)this.pos.x=~~a(b.x-this._deadwidth,this._limitwidth);else if(b.x-this.pos.x<this.deadzone.x)this.pos.x=~~c(b.x-this.deadzone.x,0)},_followV:function(b){if(b.y-this.pos.y>this._deadheight)this.pos.y=~~a(b.y-this._deadheight,this._limitheight);else if(b.y-this.pos.y<this.deadzone.y)this.pos.y=
~~c(b.y-this.deadzone.y,0)},reset:function(a,c){this.pos.x=a||0;this.pos.y=c||0;this.last.set(-1,-1);this.follow_axis=this.target=null},setDeadzone:function(a,c){this.deadzone=new me.Vector2d(~~((this.width-a)/2),~~((this.height-c)/2-0.25*c));this._deadwidth=this.width-this.deadzone.x;this._deadheight=this.height-this.deadzone.y;this.update(!0)},setBounds:function(a,c){this.limits.set(a,c);this._limitwidth=this.limits.x-this.width;this._limitheight=this.limits.y-this.height},follow:function(a,c){if(a instanceof
me.ObjectEntity)this.target=a.pos;else if(a instanceof me.Vector2d)this.target=a;else throw"melonJS: invalid target for viewport.follow";this.follow_axis=c||this.AXIS.BOTH;this.update(!0)},move:function(a,c){var d=~~(this.pos.x+a),f=~~(this.pos.y+c);if(0<=d&&d<=this._limitwidth)this.pos.x=d;if(0<=f&&f<=this._limitheight)this.pos.y=f},update:function(a){if(this.target&&a){switch(this.follow_axis){case this.AXIS.HORIZONTAL:this._followH(this.target,0<this._shake.duration);break;case this.AXIS.VERTICAL:this._followV(this.target,
0<this._shake.duration);break;case this.AXIS.BOTH:this._followH(this.target,0<this._shake.duration),this._followV(this.target,0<this._shake.duration)}a=this.last.x!=this.pos.x||this.last.y!=this.pos.y;this.last.copy(this.pos)}if(0<this._shake.duration)if(this._shake.duration-=me.timer.tick,0>this._shake.duration){if(this._shake.onComplete)this._shake.onComplete()}else{if(this._shake.axis==this.AXIS.BOTH||this._shake.axis==this.AXIS.HORIZONTAL)a=Math.random()*this._shake.intensity,this.pos.x=this.pos.x+
this.width+a<this.limits.x?this.pos.x+~~a:this.pos.x-~~a;if(this._shake.axis==this.AXIS.BOTH||this._shake.axis==this.AXIS.VERTICAL)a=Math.random()*this._shake.intensity,this.pos.y=this.pos.y+this.height+a<this.limits.y?this.pos.y+~~a:this.pos.y-~~a;a=!0}if(null!=this._fadeIn.tween||null!=this._fadeOut.tween)a=!0;return a},shake:function(a,c,d,f){d=d||this.AXIS.BOTH;if(d==this.AXIS.BOTH)if(this.width==this.limits.x)d=this.AXIS.VERTICAL;else if(this.height==this.limits.y)d=this.AXIS.HORIZONTAL;if(!(d==
this.AXIS.HORIZONTAL&&this.width==this.limits.x||d==this.AXIS.VERTICAL&&this.height==this.limits.y))this._shake.intensity=a,this._shake.duration=c,this._shake.axis=d,this._shake.onComplete=f||null},fadeOut:function(a,c,d){this._fadeOut.color=a;this._fadeOut.duration=c||1E3;this._fadeOut.alpha=1;this._fadeOut.tween=(new me.Tween(this._fadeOut)).to({alpha:0},this._fadeOut.duration).onComplete(d||null);this._fadeOut.tween.start()},fadeIn:function(a,c,d){this._fadeIn.color=a;this._fadeIn.duration=c||
1E3;this._fadeIn.alpha=0;this._fadeIn.tween=(new me.Tween(this._fadeIn)).to({alpha:1},this._fadeIn.duration).onComplete(d||null);this._fadeIn.tween.start()},getWidth:function(){return this.width},getHeight:function(){return this.height},focusOn:function(a){this.pos.x=a.x-0.5*this.width;this.pos.y=a.y-0.5*this.height},isVisible:function(a){return a.overlaps(this)},draw:function(a){if(this._fadeIn.tween&&(me.sys.enableWebGL?me.video.clearSurface(a,me.utils.HexToRGB(this._fadeIn.color,this._fadeIn.alpha)):
(a.globalAlpha=this._fadeIn.alpha,me.video.clearSurface(a,me.utils.HexToRGB(this._fadeIn.color)),a.globalAlpha=1),1==this._fadeIn.alpha))this._fadeIn.tween=null;if(this._fadeOut.tween&&(me.sys.enableWebGL?me.video.clearSurface(a,me.utils.HexToRGB(this._fadeOut.color,this._fadeOut.alpha)):(a.globalAlpha=this._fadeOut.alpha,me.video.clearSurface(a,me.utils.HexToRGB(this._fadeOut.color)),a.globalAlpha=1),0==this._fadeOut.alpha))this._fadeOut.tween=null}})})(window);
(function(a,c){var b=Math.min;me.ObjectSettings={name:null,image:null,transparent_color:null,spritewidth:null,spriteheight:null,type:0,collidable:!1};me.entityPool=function(){var a={},b={};a.init=function(){a.add("me.LevelEntity",me.LevelEntity);a.add("me.ObjectEntity",me.ObjectEntity);a.add("me.CollectableEntity",me.CollectableEntity);a.add("me.InvisibleEntity",me.InvisibleEntity)};a.add=function(a,d){b[a.toLowerCase()]=d};a.newIstanceOf=function(a){return!b[a.name.toLowerCase()]?(alert("cannot instance entity of type '"+
a.name+"': Class not found!"),null):new (b[a.name.toLowerCase()])(a.x,a.y,a)};return a}();var e=me.Rect.extend({init:function(a,b,c){this.image=me.loader.getImage(a);if(null==this.image)throw"melonJS: image "+a+" for Parallax Layer not found!";this.parent(new me.Vector2d(0,0),this.image.width,this.image.height);this.baseOffset=0;this.z=c||0;this.scrollspeed=b;this.vp_width=me.game.viewport.width},draw:function(a,f,c){var e=0,h=b(this.width-f,this.vp_width);do a.drawImage(this.image,f,0,h,this.height,
e,c,h,this.height),e+=h,f=0,h=b(this.width,this.vp_width-e);while(e<this.vp_width)}});me.ParallaxBackgroundEntity=me.Rect.extend({init:function(a){this.parent(new me.Vector2d(0,0),0,0);this.name="parallaxBackgroundEntity";this.visible=!0;this.z=a||0;this.vp=me.game.viewport.pos;this.lastx=this.vp.x;this.parallaxLayers=[];this.updated=!0},addLayer:function(a,b,c){var j=this.parallaxLayers.length;this.parallaxLayers.push(new e(a,b,c));if(this.parallaxLayers[j].width>this.width)this.width=this.parallaxLayers[j].width;
if(this.parallaxLayers[j].height>this.height)this.height=this.parallaxLayers[j].height},clearTile:function(){},update:function(){return this.updated},getRect:function(){return new me.Rect(this.vp.clone(),this.width,this.height)},draw:function(a){var b=this.vp.x;if(b>this.lastx)for(var c=0,e;e=this.parallaxLayers[c++];)e.baseOffset=(e.baseOffset+e.scrollspeed*me.timer.tick)%e.width,e.draw(a,~~e.baseOffset,0),this.lastx=b,this.updated=!0;else if(b<this.lastx)for(c=0;e=this.parallaxLayers[c++];)e.baseOffset=
(e.width+(e.baseOffset-e.scrollspeed*me.timer.tick))%e.width,e.draw(a,~~e.baseOffset,0),this.lastx=b,this.updated=!0;else for(c=0;e=this.parallaxLayers[c++];)e.draw(a,~~e.baseOffset,0),this.lastx=b,this.updated=!1}});me.SpriteObject=me.Rect.extend({scale:null,scaleFlag:!1,lastflipX:!1,lastflipY:!1,z:0,offset:null,autodestroy:!0,visible:!0,image:null,collisionBox:null,flickering:!1,flickerTimer:-1,flickercb:null,flickerState:!1,vp:null,init:function(a,b,c,e,h){this.parent(new me.Vector2d(a,b),e||c.width,
h||c.height);this.image=c;this.scale=new me.Vector2d(1,1);this.collisionBox=new me.Rect(this.pos,this.width,this.height);this.vp=me.game.viewport;this.offset=new me.Vector2d(0,0);this.spritecount=new me.Vector2d(~~(this.image.width/this.width),~~(this.image.height/this.height))},setTransparency:function(a){a="#"==a.charAt(0)?a.substring(1,7):a;this.image=me.video.applyRGBFilter(this.image,"transparent",a.toUpperCase()).canvas},isFlickering:function(){return this.flickering},flicker:function(a,b){this.flickerTimer=
a;if(0>this.flickerTimer)this.flickering=!1,this.flickercb=null;else if(!this.flickering)this.flickercb=b,this.flickering=!0},flipX:function(a){if(a!=this.lastflipX)this.lastflipX=a,this.scale.x=-this.scale.x,this.scaleFlag=1!=this.scale.x||1!=this.scale.y,this.collisionBox.flipX(this.width)},flipY:function(a){if(a!=this.lastflipY)this.lastflipY=a,this.scale.y=-this.scale.y,this.scaleFlag=1!=this.scale.x||1!=this.scale.y,this.collisionBox.flipY(this.height)},resize:function(a){if(0<a)this.scale.x=
0>this.scale.x?-a:a,this.scale.y=0>this.scale.y?-a:a,this.scaleFlag=1!=this.scale.x||1!=this.scale.y},update:function(){return this.flickering?(this.flickerTimer-=me.timer.tick,0>this.flickerTimer&&(this.flickercb&&this.flickercb(),this.flicker(-1)),!0):!1},draw:function(a){if(this.flickering&&(this.flickerState=!this.flickerState,!this.flickerState))return;var b=~~(this.pos.x-this.vp.pos.x),c=~~(this.pos.y-this.vp.pos.y);this.scaleFlag&&(a.translate(b+this.hWidth,c+this.hHeight),a.scale(this.scale.x,
this.scale.y),a.translate(-this.hWidth,-this.hHeight),b=c=0);a.drawImage(this.image,this.offset.x,this.offset.y,this.width,this.height,b,c,this.width,this.height);this.scaleFlag&&a.setTransform(1,0,0,1,0,0);me.debug.renderHitBox&&(this.parent(a,"blue"),this.collisionBox.draw(a,"red"))},destroy:function(){if(this.autodestroy)this.onDestroyEvent();return this.autodestroy},onDestroyEvent:function(){}});me.AnimationSheet=me.SpriteObject.extend({fpscount:0,animationspeed:0,init:function(a,b,c,e,h){this.anim=
[];this.current=this.resetAnim=null;this.parent(a,b,c,e,h);if(1==this.spritecount.x*this.spritecount.y)this.setCurrentSprite=function(){};this.animationspeed=me.sys.fps/10;this.addAnimation("default",null);this.setCurrentAnimation("default")},addAnimation:function(a,b){this.anim[a]={name:a,frame:[],idx:0,length:0};if(null==b)for(var b=[],c=0,e=this.spritecount.x*this.spritecount.y;c<e;c++)b[c]=c;c=0;for(e=b.length;c<e;c++)this.anim[a].frame[c]=new me.Vector2d(this.width*(b[c]%this.spritecount.x),
this.height*~~(b[c]/this.spritecount.x));this.anim[a].length=this.anim[a].frame.length},setCurrentAnimation:function(a,b){this.current=this.anim[a];this.resetAnim=b||null;this.offset=this.current.frame[this.current.idx]},isCurrentAnimation:function(a){return this.current.name==a},setCurrentSprite:function(a){this.current.idx=a;this.offset=this.current.frame[a];0==this.current.idx&&this.resetAnim&&("string"==typeof this.resetAnim?this.setCurrentAnimation(this.resetAnim):"function"==typeof this.resetAnim&&
this.resetAnim())},update:function(){this.parent();return this.visible&&this.fpscount++>this.animationspeed?(this.setCurrentSprite(++this.current.idx%this.current.length),this.fpscount=0,!0):!1}});me.ObjectEntity=me.AnimationSheet.extend({GUID:null,type:0,collidable:!1,init:function(a,b,g){this.parent(a,b,"string"==typeof g.image?me.loader.getImage(g.image):g.image,g.spritewidth,g.spriteheight);g.transparent_color&&this.setTransparency(g.transparent_color);this.GUID=me.utils.createGUID();this.name=
g.name?g.name.toLowerCase():"";this.pos.set(a,me.game.currentLevel?b+me.game.currentLevel.tileheight-this.height:b);this.vel=new me.Vector2d;this.accel=new me.Vector2d;this.friction=new me.Vector2d;this.maxVel=new me.Vector2d(1E3,1E3);this.gravity=me.sys.gravity!=c?me.sys.gravity:0.98;this.alive=this.isEntity=!0;this.falling=!1;this.jumping=!0;this.slopeY=0;this.onladder=this.onslope=!1;this.collidable=g.collidable||!1;this.type=g.type||0;this.collisionMap=me.game.collisionMap;this.canBreakTile=!1;
this.onTileBreak=null},updateColRect:function(a,b,c,e){this.collisionBox.adjustSize(a,b,c,e)},checkCollision:function(a){var b=this.collisionBox.collideVsAABB(a.collisionBox);return 0!=b.x||0!=b.y?(this.onCollision(b,a),b.type=this.type,b.obj=this,b):null},onCollision:function(){this.collidable&&this.type==me.game.COLLECTABLE_OBJECT&&me.game.remove(this)},setVelocity:function(a,b){this.accel.x=0!=a?a:this.accel.x;this.accel.y=0!=b?b:this.accel.y;this.setMaxVelocity(a,b)},setMaxVelocity:function(a,
b){this.maxVel.x=a;this.maxVel.y=b},setFriction:function(a,b){this.friction.x=a||0;this.friction.y=b||0},doWalk:function(a){this.flipX(a);this.vel.x+=a?-this.accel.x*me.timer.tick:this.accel.x*me.timer.tick},doClimb:function(a){return this.onladder?(this.vel.y=a?-this.accel.x*me.timer.tick:this.accel.x*me.timer.tick,!0):!1},doJump:function(){return!this.jumping&&!this.falling?(this.vel.y=-this.maxVel.y*me.timer.tick,this.jumping=!0):!1},forceJump:function(){this.jumping=this.falling=!1;this.doJump()},
distanceTo:function(a){var b=this.pos.x+this.hWidth-(a.pos.x+a.hWidth),a=this.pos.y+this.hHeight-(a.pos.y+a.hHeight);return Math.sqrt(b*b+a*a)},checkSlope:function(a,b){this.pos.y=a.pos.y-this.height;this.slopeY=b?a.height-(this.collisionBox.right+this.vel.x-a.pos.x):this.collisionBox.left+this.vel.x-a.pos.x;this.vel.y=0;this.pos.y+=this.slopeY.clamp(0,a.height)},computeVelocity:function(a){if(this.gravity)a.y+=!this.onladder?this.gravity*me.timer.tick:0,this.jumping=(this.falling=0<a.y)?!1:this.jumping;
if(this.friction.x)a.x=me.utils.applyFriction(a.x,this.friction.x);if(this.friction.y)a.y=me.utils.applyFriction(a.y,this.friction.y);if(0!=a.y)a.y=a.y.clamp(-this.maxVel.y,this.maxVel.y);if(0!=a.x)a.x=a.x.clamp(-this.maxVel.x,this.maxVel.x)},updateMovement:function(){this.computeVelocity(this.vel);var a=this.collisionMap.checkCollision(this.collisionBox,this.vel);this.onslope=a.yprop.isSlope||a.xprop.isSlope;this.onladder=!1;if(a.y)if(this.onladder=a.yprop.isLadder,0<a.y)if(a.yprop.isSolid||a.yprop.isPlatform&&
this.collisionBox.bottom-1<=a.ytile.pos.y)this.pos.y=~~this.pos.y,this.vel.y=this.falling?a.ytile.pos.y-this.collisionBox.bottom:0,this.falling=!1;else if(a.yprop.isSlope&&!this.jumping)this.checkSlope(a.ytile,a.yprop.isLeftSlope),this.falling=!1;else{if(a.yprop.isBreakable)if(this.canBreakTile){if(me.game.currentLevel.clearTile(a.ytile.row,a.ytile.col),this.onTileBreak)this.onTileBreak()}else this.pos.y=~~this.pos.y,this.vel.y=this.falling?a.ytile.pos.y-this.collisionBox.bottom:0,this.falling=!1}else if(0>
a.y&&!a.yprop.isPlatform&&!a.yprop.isLadder)this.falling=!0,this.vel.y=0;if(a.x)if(this.onladder=a.xprop.isLadder,a.xprop.isSlope&&!this.jumping)this.checkSlope(a.xtile,a.xprop.isLeftSlope),this.falling=!1;else if(!a.xprop.isPlatform&&!a.xprop.isLadder)if(a.xprop.isBreakable&&this.canBreakTile){if(me.game.currentLevel.clearTile(a.xtile.row,a.xtile.col),this.onTileBreak)this.onTileBreak()}else this.vel.x=0;this.pos.add(this.vel);return a}});me.CollectableEntity=me.ObjectEntity.extend({init:function(a,
b,c){this.parent(a,b,c);this.collidable=!0;this.type=me.game.COLLECTABLE_OBJECT}});me.InvisibleEntity=me.Rect.extend({GUID:null,z:0,collisionBox:null,init:function(a,b,c){this.parent(new me.Vector2d(a,b),c.width,c.height);this.collisionBox=new me.Rect(this.pos,c.width,c.height);this.GUID=me.utils.createGUID();this.name=c.name?c.name.toLowerCase():"";this.isEntity=this.collidable=this.visible=!0},updateColRect:function(a,b,c,e){this.collisionBox.adjustSize(a,b,c,e)},checkCollision:function(a){var b=
this.collisionBox.collideVsAABB(a.collisionBox);return 0!=b.x||0!=b.y?(this.onCollision(b,a),b.type=this.type,b.obj=this,b):null},onCollision:function(){this.collidable&&this.type==me.game.COLLECTABLE_OBJECT&&me.game.remove(this)},destroy:function(){this.onDestroyEvent();return!0},onDestroyEvent:function(){},update:function(){return!1},draw:function(a){if(me.debug.renderHitBox)a.strokeStyle="blue",a.strokeRect(this.pos.x-me.game.viewport.pos.x,this.pos.y-me.game.viewport.pos.y,this.width,this.height),
this.collisionBox.draw(a)}});me.LevelEntity=me.InvisibleEntity.extend({init:function(a,b,c){this.parent(a,b,c);this.nextlevel=c.to;this.fade=c.fade;this.duration=c.duration;this.fading=!1;this.gotolevel=c.to},onFadeComplete:function(){me.levelDirector.loadLevel(this.gotolevel);me.game.viewport.fadeOut(this.fade,this.duration)},goTo:function(a){this.gotolevel=a||this.nextlevel;if(this.fade&&this.duration){if(!this.fading)this.fading=!0,me.game.viewport.fadeIn(this.fade,this.duration,this.onFadeComplete.bind(this))}else me.levelDirector.loadLevel(this.gotolevel)},
onCollision:function(){this.goTo()}})})(window);
(function(){me.Font=Object.extend({ALIGN:{LEFT:"left",CENTER:"center",RIGHT:"right"},font:null,height:null,color:null,align:null,init:function(a,c,b,e){this.set(a,c,b,e)},bold:function(){this.font="bold "+this.font},italic:function(){this.font="italic "+this.font},set:function(a,c,b,e){this.font=""+c+"px "+a;this.height=c;this.color=b;this.align=e||"top"},getRect:function(){return new me.Rect(new Vector2d(0,0),0,0)},measureText:function(a,c){a.font=this.font;a.fillStyle=this.color;a.textBaseLine=
this.align;var b=a.measureText(c);b.height=this.height;return b},draw:function(a,c,b,e){a.font=this.font;a.fillStyle=this.color;a.textBaseLine=this.align;a.fillText(c,~~b,~~e)}});me.BitmapFont=me.Font.extend({size:null,sSize:null,firstChar:32,charCount:0,init:function(a,c,b,e){this.parent(a,null,null);this.size=new me.Vector2d;this.sSize=new me.Vector2d;this.firstChar=e||32;this.loadFontMetrics(a,c);this.align=this.ALIGN.RIGHT;b&&this.resize(b)},loadFontMetrics:function(a,c){this.font=me.loader.getImage(a);
this.size.x=c.x||c;this.size.y=c.y||this.font.height;this.sSize.copy(this.size);this.charCount=~~(this.font.width/this.size.x)},set:function(a,c){this.align=a;c&&this.resize(c)},resize:function(a){this.sSize.copy(this.size);this.sSize.x*=a;this.sSize.y*=a},measureText:function(a){return{width:a.length*this.sSize.x,height:this.sSize.y}},draw:function(a,c,b,e){c=new String(c);switch(this.align){case this.ALIGN.RIGHT:b-=this.measureText(c).width;break;case this.ALIGN.CENTER:b-=0.5*this.measureText(c).width}for(var d=
0,f=c.length;d<f;d++){var g=c.charCodeAt(d)-this.firstChar;a.drawImage(this.font,this.size.x*(g%this.charCount),this.size.y*~~(g/this.charCount),this.size.x,this.size.y,~~b,~~e,this.sSize.x,this.sSize.y);b+=this.sSize.x}}})})(window);
(function(){me.GUI_Object=me.SpriteObject.extend({isClickable:!0,updated:!1,init:function(a,c,b){this.parent(a,c,"string"==typeof b.image?me.loader.getImage(b.image):b.image,b.spritewidth,b.spriteheight);me.input.registerMouseEvent("mousedown",this.collisionBox,this.clicked.bind(this))},update:function(){return this.updated?(this.updated=!1,!0):!1},clicked:function(){if(this.isClickable)return this.updated=!0,this.onClicked()},onClicked:function(){return!0},onDestroyEvent:function(){me.input.releaseMouseEvent("mousedown",
this.collisionBox)}})})(window);
(function(a,c){me.HUD_Item=Object.extend({init:function(a,c,d){this.pos=new me.Vector2d(a||0,c||0);this.visible=!0;this.defaultvalue=d||0;this.value=d||0;this.updated=!0},reset:function(){this.set(this.defaultvalue)},set:function(a){this.value=a;return this.updated=!0},update:function(a){return this.set(this.value+a)},draw:function(){}});me.HUD_Object=me.Rect.extend({init:function(a,c,d,f,g){this.parent(new me.Vector2d(a||0,c||0),d||me.video.getWidth(),f||me.video.getHeight());this.bgcolor=g;this.HUDItems=
{};this.HUDobj=[];this.objCount=0;this.HUD_invalidated=this.visible=!0;this.HUDCanvasSurface=me.video.createCanvasSurface(this.width,this.height);this.z=999},addItem:function(a,c){this.HUDItems[a]=c;this.HUDobj.push(this.HUDItems[a]);this.objCount++;this.HUD_invalidated=!0},removeItem:function(a){if(this.HUDItems[a])this.HUDobj.splice(this.HUDobj.indexOf(this.HUDItems[a]),1),this.HUDItems[a]=null,this.objCount--,this.HUD_invalidated=!0},setItemValue:function(a,c){if(this.HUDItems[a]&&!0==this.HUDItems[a].set(c))this.HUD_invalidated=
!0},updateItemValue:function(a,c){if(this.HUDItems[a]&&!0==this.HUDItems[a].update(c))this.HUD_invalidated=!0},getItemValue:function(a){return this.HUDItems[a]?this.HUDItems[a].value:0},update:function(){return this.HUD_invalidated},reset:function(a){a!=c?(this.HUDItems[a]&&this.HUDItems[a].reset(),this.HUD_invalidated=!0):this.resetAll()},resetAll:function(){for(var a=this.objCount,c;a--,c=this.HUDobj[a];)c.reset();this.HUD_invalidated=!0},getRect:function(){p=this.pos.clone();p.add(me.game.viewport.pos);
return new me.Rect(p,this.width,this.height)},draw:function(a){if(this.HUD_invalidated){this.bgcolor?me.video.clearSurface(this.HUDCanvasSurface,this.bgcolor):this.HUDCanvasSurface.canvas.width=this.HUDCanvasSurface.canvas.width;for(var c=this.objCount,d;c--,d=this.HUDobj[c];)if(d.visible&&(d.draw(this.HUDCanvasSurface,0,0),d.updated))d.updated=!1}a.drawImage(this.HUDCanvasSurface.canvas,this.pos.x,this.pos.y);this.HUD_invalidated=!1}})})(window);
(function(){me.audio=function(){function a(){var a=0;if(me.sys.sound){if(-1!=j.search(/mp3/i)&&d.capabilities.mp3)return g[a];if(-1!=j.search(/ogg/i)&&d.capabilities.ogg||-1!=j.search(/wav/i)&&d.capabilities.wav)return g[++a];i=!1;return-1}i=!1}function c(a){for(var a=f[a],b=0,c;c=a[b++];)if(c.ended||!c.currentTime)return c.currentTime=m,c;a[0].pause();a[0].currentTime=m;return a[0]}function b(a,b,d){var f=c(a.toLowerCase());f.loop=b||!1;f.play();d&&!b&&f.addEventListener("ended",function(a){f.removeEventListener("ended",
arguments.callee,!1);d()},!1)}function e(a,b,c){c&&!b&&setTimeout(c,2E3)}var d={},f=[],g=["mp3","ogg","wav"],j=null,h=-1,k=null,l=null,i=!0,m=0,n=0;d.capabilities={mp3:!1,ogg:!1,ma4:!1,wav:!1};d.init=function(c){j=c?new String(c):new String("mp3");h=a();d.play=i?b:e;return i};d.setLoadCallback=function(a){k=a};d.isAudioEnable=function(){return i};d.enable=function(){i=me.sys.sound;d.play=i?b:e};d.disable=function(){i=!1;d.play=e};d.load=function(a){if(-1==h)return 0;var b=new Audio(a.src+a.name+"."+
h+me.nocache);b.preload="auto";b.addEventListener("canplaythrough",function(b){this.removeEventListener("canplaythrough",arguments.callee,!1);var c=a.name,d=a.channel;n=0;if(1<d)for(var g=f[c][0],e=1;e<d;e++){var i=g.cloneNode(!0);if(0==i.currentSrc.length)i.src=g.src;f[c][e]=i;f[c][e].load()}k&&k()},!1);b.addEventListener("error",function(){var b=a.name;if(3<n++)if(b="melonJS: failed loading "+b+"."+h,!1===me.sys.stopOnAudioError)me.audio.disable(),k&&k(),console.log(b+", disabling audio");else throw b;
else f[b][0].load()},!1);b.src=a.src+a.name+"."+h+me.nocache;b.load();f[a.name]=[b];return 1};d.stop=function(a){if(i)for(var a=f[a.toLowerCase()],b=a.length;b--;)a[b].pause(),a[b].currentTime=m};d.pause=function(a){if(i)for(var a=f[a.toLowerCase()],b=a.length;b--;)a[b].pause()};d.playTrack=function(a){if(i&&(null!=l&&d.stopTrack(),l=c(a.toLowerCase())))l.loop=!0,l.play()};d.stopTrack=function(){i&&l&&(l.pause(),l=null)};d.pauseTrack=function(){i&&l&&l.pause()};d.resumeTrack=function(){i&&l&&l.play()};
return d}()})(window);
(function(){me.timer=function(){var a={},c=null,b=!1,e=0,d=0,f=0,g=0,j=0,h=Math.ceil(1E3/me.sys.fps),k=1.25*(1E3/me.sys.fps);a.tick=1;a.init=function(){c=document.getElementById("framecounter");b=null!==c;a.reset()};a.reset=function(){g=f=(new Date).getTime();e=d=0};a.getTime=function(){return g};a.update=function(){f=g;g=(new Date).getTime();j=g-f;if(b&&(e++,d+=j,0==e%10)){var l=(~~(1E3*e/d)).clamp(0,me.sys.fps);c.replaceChild(document.createTextNode("("+l+"/"+me.sys.fps+" fps)"),c.firstChild);e=
d=0}a.tick=j>k&&me.sys.interpolation?j/h:1};return a}();me.video=function(){var a={},c=null,b=null,e=null,d=null,f=null,g=!1,j=0,h=0;a.init=function(k,l,i,m,n){g=m||!1;me.sys.scale=!0===g?n||1:1;j=l*me.sys.scale;h=i*me.sys.scale;f=document.getElementById(k);c=document.createElement("canvas");c.setAttribute("width",j+"px");c.setAttribute("height",h+"px");c.setAttribute("border","0px solid black");f.appendChild(c);if(me.sys.enableWebGL&&window.WebGLRenderingContext)try{WebGL2D.enable(c),b=c.getContext("webgl-2d"),
me.sys.cacheImage=!0}catch(o){b=null}if(null==b){me.sys.enableWebGL=!1;if(!c.getContext)return!1;b=c.getContext("2d")}g?(d=a.createCanvasSurface(l,i),e=d.canvas):(d=b,e=b.canvas);return!0};a.getWrapper=function(){return f};a.getWidth=function(){return e.width};a.getPos=function(a){for(var a=a||c,b=new me.Vector2d(a.offsetLeft,a.offsetTop);a=a.offsetParent;)b.x+=a.offsetLeft,b.y+=a.offsetTop;return b};a.getHeight=function(){return e.height};a.createCanvasSurface=function(a,b){var c=document.createElement("canvas");
c.width=a||e.width;c.height=b||e.height;return c.getContext("2d")};a.getScreenCanvas=function(){return c};a.getScreenFrameBuffer=function(){return d};a.updateDisplaySize=function(a){if(g)me.sys.scale=a?a:document.getElementById("screen size").value,j=e.width*me.sys.scale,h=e.height*me.sys.scale,c.width=j,c.height=h};a.clearSurface=function(a,b){a.fillStyle=b;a.fillRect(0,0,a.canvas.width,a.canvas.height)};a.scale=function(a,b){a.translate(-(a.canvas.width*b-a.canvas.width>>1),-(a.canvas.height*b-
a.canvas.height>>1));a.scale(b,b)};a.setAlpha=function(a,b){a.globalCompositeOperation=b?"source-over":"copy"};a.blitSurface=function(){a.blitSurface=g?function(){b.drawImage(e,0,0,e.width,e.height,0,0,j,h)}:function(){};a.blitSurface()};a.applyRGBFilter=function(b,c,d){var f=a.createCanvasSurface(b.width,b.height),b=me.utils.getPixels(b),g=b.data;switch(c){case "b&w":for(var c=0,e=g.length;c<e;c+=4)d=3*g[c]+4*g[c+1]+g[c+2]>>>3,g[c]=d,g[c+1]=d,g[c+2]=d;break;case "brightness":d=Math.abs(d).clamp(0,
1);c=0;for(e=g.length;c<e;c+=4)g[c]*=d,g[c+1]*=d,g[c+2]*=d;break;case "transparent":c=0;for(e=g.length;c<e;c+=4)me.utils.RGBToHex(g[c],g[c+1],g[c+2])===d&&(g[c+3]=0);break;default:return null}f.putImageData(b,0,0);return f};return a}()})(window);
(function(a){me.input=function(){function c(){if(!w)i.mouse.pos=new me.Vector2d(0,0),i.mouse.offset=me.video.getPos(),me.sys.touch?(me.video.getScreenCanvas().addEventListener("touchmove",h,!1),me.video.getScreenCanvas().addEventListener("touchstart",k,!1),me.video.getScreenCanvas().addEventListener("touchend",k,!1)):(a.addEventListener("mousewheel",j,!1),me.video.getScreenCanvas().addEventListener("mousemove",h,!1),me.video.getScreenCanvas().addEventListener("mousedown",k,!1),me.video.getScreenCanvas().addEventListener("mouseup",
k,!1)),w=!0}function b(a){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0;a.preventDefault?a.preventDefault():a.returnValue=!1}function e(a,c){var d=m[c||a.keyCode||a.which];return d?(q[d]||(n[d]=!0,q[d]=o[d]),b(a),!1):!0}function d(a,c){var d=m[c||a.keyCode||a.which];return d?(n[d]=!1,q[d]=!1,b(a),!1):!0}function f(a){var b=i.mouse.handlers[a.type];if(b)for(var c=i.mouse.pos,d=b.length,f;(d--,f=b[d])&&!((null===f.rect||f.rect.containsPoint(c))&&!1===f.cb(a)););}function g(a,b){i.mouse.pos.set(a,
b);i.mouse.pos.sub(i.mouse.offset);1!=me.sys.scale&&i.mouse.pos.div(me.sys.scale)}function j(a){f(a);b(a)}function h(a){a.touches?g(a.touches[0].clientX,a.touches[0].clientY):g(a.pageX,a.pageY);f(a);b(a)}function k(a){"touchstart"===a.type&&g(a.touches[0].clientX,a.touches[0].clientY);var c=i.mouse.bind[a.button||0];f(a);c?"mousedown"===a.type||"touchstart"===a.type?e(a,c):d(a,c):b(a)}function l(a){i.accel=a.accelerationIncludingGravity}var i={},m=[],n=[],o=[],q=[],r=!1,w=!1,s=!1;i.accel={x:0,y:0,
z:0};i.mouse={pos:null,offset:null,LEFT:0,MIDDLE:1,RIGHT:2,bind:[3],handlers:{}};i.KEY={LEFT:37,UP:38,RIGHT:39,DOWN:40,ENTER:13,SHIFT:16,CTRL:17,ALT:18,PAUSE:19,ESC:27,SPACE:32,NUM0:48,NUM1:49,NUM2:50,NUM3:51,NUM4:52,NUM5:53,NUM6:54,NUM7:55,NUM8:56,NUM9:57,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,P:80,Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,Y:89,Z:90};i.isKeyPressed=function(a){return n[a]?(o[a]&&(q[a]=!0,n[a]=!1),!0):!1};i.keyStatus=function(a){return!0===q[a]?!0:
n[a]};i.updateKey=function(a,b){b?e({},a):d({},a)};i.bindKey=function(b,c,f){r||(a.addEventListener("keydown",e,!1),a.addEventListener("keyup",d,!1),r=!0);m[b]=c;o[c]=f?f:!1;q[c]=!1};i.unbindKey=function(a){n[m[a]]=!1;o[m[a]]=!1;m[a]=null};i.bindMouse=function(a,b){c();if(!m[b])throw"melonJS : no action defined for keycode "+b;i.mouse.bind[a]=b};i.unbindMouse=function(a){i.mouse.bind[a]=null};i.bindTouch=function(){object.bindMouse(me.input.mouse.LEFT,keycode)};i.unbindTouch=function(){i.unbindMouse(me.input.mouse.LEFT)};
i.registerMouseEvent=function(a,b,d){c();switch(a){case "mousewheel":case "mousemove":case "mousedown":case "mouseup":case "touchmove":case "touchstart":case "touchend":me.sys.touch&&("mousemove"==a?a="touchmove":"mousedown"==a?a="touchstart":"mouseup"==a&&(a="touchend"));i.mouse.handlers[a]||(i.mouse.handlers[a]=[]);i.mouse.handlers[a].push({rect:b||null,cb:d});break;default:throw"melonJS : invalid event type : "+a;}};i.releaseMouseEvent=function(a,b){switch(a){case "mousewheel":case "mousemove":case "mousedown":case "mouseup":case "touchmove":case "touchstart":case "touchend":me.sys.touch&&
("mousemove"==a?a="touchmove":"mousedown"==a?a="touchstart":"mouseup"==a&&(a="touchend"));var c=i.mouse.handlers[a];if(c)for(var d=c.length,f;d--,f=c[d];)if(f.rect===b)f.rect=f.cb=null,i.mouse.handlers[a].splice(d,1);break;default:throw"melonJS : invalid event type : "+a;}};i.watchAccelerometer=function(){return a.sys.gyro?(s||(a.addEventListener("devicemotion",l,!1),s=!0),!0):!1};i.unwatchAccelerometer=function(){s&&(a.removeEventListener("devicemotion",l,!1),s=!1)};return i}()})(window);
(function(a){var c=function(){return{decode:function(b){b=b.replace(/[^A-Za-z0-9\+\/\=]/g,"");if(me.sys.nativeBase64)return a.atob(b);for(var c=[],d,f,g,j,h,k=0;k<b.length;)d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(k++)),f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(k++)),j="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(k++)),h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(k++)),
d=d<<2|f>>4,f=(f&15)<<4|j>>2,g=(j&3)<<6|h,c.push(String.fromCharCode(d)),64!=j&&c.push(String.fromCharCode(f)),64!=h&&c.push(String.fromCharCode(g));return c=c.join("")}}}();me.utils=function(){var a={},e={},d="",f=0;a.decodeBase64=function(a){return c.decode(a)};a.decodeBase64AsArray=function(a,b){var b=b||1,d=c.decode(a),f=[],e,i,m;for(e=0,m=d.length/b;e<m;e++){f[e]=0;for(i=b-1;0<=i;--i)f[e]+=d.charCodeAt(e*b+i)<<(i<<3)}return f};a.decodeCSV=function(a,b){for(var a=a.trim().split("\n"),c=[],d=0;d<
a.length;d++){entries=a[d].split(",",b);for(var f=0;f<entries.length;f++)c.push(+entries[f])}return c};a.setNocache=function(a){me.nocache=a?"?"+parseInt(1E7*Math.random()):""};a.HexToRGB=function(a,b){a="#"==a.charAt(0)?a.substring(1,7):a;null==e[a]&&(e[a]=parseInt(a.substring(0,2),16)+","+parseInt(a.substring(2,4),16)+","+parseInt(a.substring(4,6),16));return(b?"rgba(":"rgb(")+e[a]+(b?","+b+")":")")};a.RGBToHex=function(a,b,c){return a.toHex()+b.toHex()+c.toHex()};a.getPixels=function(a){if(a instanceof
HTMLImageElement){var b=me.video.createCanvasSurface(a.width,a.height);b.drawImage(a,0,0);return b.getImageData(0,0,a.width,a.height)}return a.getContext("2d").getImageData(0,0,a.width,a.height)};a.resetGUID=function(a){d=a.toString().toUpperCase().toHex();f=0};a.createGUID=function(){return d+"-"+f++};a.applyFriction=function(a,b){return 0>a+b?a+b*me.timer.tick:0<a-b?a-b*me.timer.tick:0};return a}()})(window);
(function(a,c){function b(a){this.defaultvalue=a||0;this.value=a||0;this.updated=!0}b.prototype.reset=function(){this.set(this.defaultvalue)};b.prototype.update=function(a){return this.set(this.value+a)};b.prototype.set=function(a){this.value=a;return this.updated=!0};me.gamestat=function(){var a={},d={},f=[],g=0;a.add=function(a,c){d[a]=new b(c);f.push(d[a]);g++};a.updateValue=function(a,b){d[a]&&d[a].update(b)};a.setValue=function(a,b){d[a]&&d[a].set(b)};a.getItemValue=function(a){return d[a]?d[a].value:
0};a.reset=function(b){b!=c?d[b]&&d[b].reset():a.resetAll()};a.resetAll=function(){for(var a=g,b;a--,b=f[a];)b.reset()};return a}()})(window);
(function(a,c){var b=/^.*(\\|\/|\:)/,e=/\.[^\.]*$/;me.LevelConstants={COLLISION_MAP:"collision",PARALLAX_MAP:"parallax"};me.Tile=me.Rect.extend({tileId:null,init:function(a,b,c,e,h){this.parent(new me.Vector2d(a*c,b*e),c,e);this.tileId=h;this.row=a;this.col=b}});me.Tileset=Object.extend({init:function(a,c,g,j,h,k){this.name=a;this.tilewidth=c;this.tileheight=g;this.spacing=j;this.margin=h;(this.image=k?me.loader.getImage(k.replace(b,"").replace(e,"")):null)||console.log("melonJS: '"+k+"' file for tileset '"+
this.name+"' not found!");this.type={SOLID:"solid",PLATFORM:"platform",L_SLOPE:"lslope",R_SLOPE:"rslope",LADDER:"ladder",BREAKABLE:"breakable"};this.TileProperties=[];this.tileXOffset=[];this.tileYOffset=[];if(this.image)this.hTileCount=~~((this.image.width-this.margin)/(this.tilewidth+this.spacing)),this.vTileCount=~~((this.image.height-this.margin)/(this.tileheight+this.spacing))},getPropertyList:function(){return{isCollidable:!1,isSolid:!1,isPlatform:!1,isSlope:!1,isLeftSlope:!1,isRightSlope:!1,
isLadder:!1,isBreakable:!1}},getTileProperties:function(a){return this.TileProperties[a]},isTileCollidable:function(a){return this.TileProperties[a].isCollidable},getTileImage:function(a){var b=me.video.createCanvasSurface(this.tilewidth,this.tileheight);this.drawTile(b,0,0,a);return b.canvas},getTileOffsetX:function(a){null==this.tileXOffset[a]&&(this.tileXOffset[a]=this.margin+(this.spacing+this.tilewidth)*(a%this.hTileCount));return this.tileXOffset[a]},getTileOffsetY:function(a){null==this.tileYOffset[a]&&
(this.tileYOffset[a]=this.margin+(this.spacing+this.tileheight)*~~(a/this.hTileCount));return this.tileYOffset[a]},drawTile:function(a,b,c,e,h,k,l){if(h||k||l){var i=1,m=0,n=0,o=1,q=b,r=c,b=c=0;l&&(i=0,n=m=1,o=0,r+=this.tileheight-this.tilewidth);h&&(i=-i,n=-n,q+=l?this.tileheight:this.tilewidth);k&&(m=-m,o=-o,r+=l?this.tilewidth:this.tileheight);a.setTransform(i,m,n,o,q,r)}a.drawImage(this.image,this.getTileOffsetX(e),this.getTileOffsetY(e),this.tilewidth,this.tileheight,b,c,this.tilewidth,this.tileheight);
(h||k||l)&&a.setTransform(1,0,0,1,0,0)}});CollisionTiledLayer=Object.extend({init:function(a,b){this.realwidth=a;this.realheight=b;this.isCollisionMap=!0},checkCollision:function(a,b){var c=0>b.x?a.left+b.x:a.right+b.x,e=0>b.y?a.top+b.y:a.bottom+b.y,h={x:0,y:0,xprop:{},yprop:{}};if(0>=c||c>=this.realwidth)h.x=b.x;if(0>=e||e>=this.realheight)h.y=b.y;return h}});me.TiledLayer=Object.extend({init:function(a,b,c,e,h,k){this.width=a;this.height=b;this.tilewidth=c;this.tileheight=e;this.realwidth=this.width*
this.tilewidth;this.realheight=this.height*this.tileheight;this.z=k;this.name=null;this.visible=!1;this.layerData=null;this.xLUT={};this.yLUT={};this.tileset=(this.tilesets=h)?this.tilesets.getTilesetByIndex(0):null},initArray:function(a){this.layerData=[];for(var b=0;b<this.width+1;b++){this.layerData[b]=[];for(var c=0;c<this.height+1;c++)this.layerData[b][c]=null}if(a){for(b=0;b<this.width*this.tilewidth;b++)this.xLUT[b]=~~(b/this.tilewidth);for(c=0;c<this.height*this.tileheight;c++)this.yLUT[c]=
~~(c/this.tileheight)}},getTileId:function(a,b){var c=this.layerData[this.xLUT[a]][this.yLUT[b]];return c?c.tileId:null},getTile:function(a,b){return this.layerData[this.xLUT[a]][this.yLUT[b]]},setTile:function(a,b,c){this.layerData[a][b]=new me.Tile(a,b,this.tilewidth,this.tileheight,c)},clearTile:function(a,b){this.layerData[a][b]=null},checkCollision:function(a,b){var e=0>b.x?~~(a.left+b.x):Math.ceil(a.right-1+b.x),j=0>b.y?~~(a.top+b.y):Math.ceil(a.bottom-1+b.y),h={x:0,xtile:c,xprop:{},y:0,ytile:c,
yprop:{}};if(0>=e||e>=this.realwidth)h.x=b.x;else if(0!=b.x)if(h.xtile=this.getTile(e,Math.ceil(a.bottom-1)),h.xtile&&this.tileset.isTileCollidable(h.xtile.tileId))h.x=b.x,h.xprop=this.tileset.getTileProperties(h.xtile.tileId);else if(h.xtile=this.getTile(e,~~a.top),h.xtile&&this.tileset.isTileCollidable(h.xtile.tileId))h.x=b.x,h.xprop=this.tileset.getTileProperties(h.xtile.tileId);if(0!=b.y)if(h.ytile=this.getTile(0>b.x?~~a.left:Math.ceil(a.right-1),j),h.ytile&&this.tileset.isTileCollidable(h.ytile.tileId))h.y=
b.y||1,h.yprop=this.tileset.getTileProperties(h.ytile.tileId);else if(h.ytile=this.getTile(0>b.x?Math.ceil(a.right-1):~~a.left,j),h.ytile&&this.tileset.isTileCollidable(h.ytile.tileId))h.y=b.y||1,h.yprop=this.tileset.getTileProperties(h.ytile.tileId);return h},update:function(){return!1}});me.TileMap=Object.extend({init:function(a,b){this.pos=new me.Vector2d(a,b);this.z=0;this.name=null;this.height=this.width=0;this.realheight=this.realwidth=-1;this.tileheight=this.tilewidth=0;this.tilesets=null;
this.mapLayers=[];this.objectGroups=[];this.initialized=!1},reset:function(){this.tilesets=null;this.mapLayers.length=0;this.objectGroups.length=0;this.initialized=!1},getObjectGroupByName:function(a){return this.objectGroups[a]},getObjectGroups:function(){return this.objectGroups},getLayerByName:function(a){for(var b=null,a=a.trim().toLowerCase(),c=this.mapLayers.length;c--;)if(this.mapLayers[c].name.toLowerCase().contains(a)){b=this.mapLayers[c];break}a.toLowerCase().contains(me.LevelConstants.COLLISION_MAP)&&
null==b&&(b=new CollisionTiledLayer(me.game.currentLevel.realwidth,me.game.currentLevel.realheight));return b},clearTile:function(a,b){for(var c=this.mapLayers.length;c--;)(this.mapLayers[c].visible||this.mapLayers[c].isCollisionMap)&&this.mapLayers[c].clearTile(a,b)},addTo:function(a){this.visible&&a.add(this);for(var b=this.mapLayers.length;b--;)this.mapLayers[b].visible&&a.add(this.mapLayers[b])},update:function(){return!1}});me.levelDirector=function(){var a={},b={},e=[],j=0;a.reset=function(){};
a.addLevel=function(){throw"melonJS: no level loader defined";};a.addTMXLevel=function(a,c){if(null==b[a])b[a]=new me.TMXTileMap(a,0,0),b[a].name=a,e[e.length]=a;c&&c()};a.loadLevel=function(a){a=a.toString().toLowerCase();if(b[a]===c)throw"melonJS: level "+a+" not found";if(b[a]instanceof me.TMXTileMap){var d=me.state.isRunning();d&&me.state.pause();me.game.reset();me.utils.resetGUID(a);b[a].reset();b[a].load();j=e.indexOf(a);me.game.loadTMXLevel(b[a]);d&&me.state.resume()}else throw"melonJS: no level loader defined";
return!0};a.getCurrentLevelId=function(){return e[j]};a.reloadLevel=function(){return a.loadLevel(a.getCurrentLevelId())};a.nextLevel=function(){return j+1<e.length?a.loadLevel(e[j+1]):!1};a.previousLevel=function(){return 0<=j-1?a.loadLevel(e[j-1]):!1};return a}()})(window);
(function(){me.TMX_TAG_MAP="map";me.TMX_TAG_NAME="name";me.TMX_TAG_VALUE="value";me.TMX_TAG_VERSION="version";me.TMX_TAG_ORIENTATION="orientation";me.TMX_TAG_WIDTH="width";me.TMX_TAG_HEIGHT="height";me.TMX_TAG_OPACITY="opacity";me.TMX_TAG_TRANS="trans";me.TMX_TAG_TILEWIDTH="tilewidth";me.TMX_TAG_TILEHEIGHT="tileheight";me.TMX_TAG_TILEOFFSET="tileoffset";me.TMX_TAG_FIRSTGID="firstgid";me.TMX_TAG_GID="gid";me.TMX_TAG_TILE="tile";me.TMX_TAG_ID="id";me.TMX_TAG_DATA="data";me.TMX_TAG_COMPRESSION="compression";
me.TMX_TAG_ENCODING="encoding";me.TMX_TAG_ATTR_BASE64="base64";me.TMX_TAG_CSV="csv";me.TMX_TAG_SPACING="spacing";me.TMX_TAG_MARGIN="margin";me.TMX_TAG_PROPERTIES="properties";me.TMX_TAG_PROPERTY="property";me.TMX_TAG_IMAGE="image";me.TMX_TAG_SOURCE="source";me.TMX_TAG_VISIBLE="visible";me.TMX_TAG_TILESET="tileset";me.TMX_TAG_LAYER="layer";me.TMX_TAG_OBJECTGROUP="objectgroup";me.TMX_TAG_OBJECT="object";me.TMX_TAG_X="x";me.TMX_TAG_Y="y";me.TMX_TAG_WIDTH="width";me.TMX_TAG_HEIGHT="height"})(window);
(function(){me.TMXUtils=function(){return{setTMXProperties:function(a,c){var b=c.getElementsByTagName(me.TMX_TAG_PROPERTIES)[0];if(b)for(var b=b.getElementsByTagName(me.TMX_TAG_PROPERTY),e=0;e<b.length;e++){var d=me.XMLParser.getStringAttribute(b[e],me.TMX_TAG_NAME),f=me.XMLParser.getStringAttribute(b[e],me.TMX_TAG_VALUE);!f||f.isBoolean()?f=f?"true"==f:!0:f.isNumeric()&&(f=parseInt(f));a[d]=f}}}}()})(window);
(function(){me.TMXOBjectGroup=Object.extend({init:function(a,c,b,e){this.objects=[];this.name=a;this.width=me.XMLParser.getIntAttribute(c,me.TMX_TAG_WIDTH);this.height=me.XMLParser.getIntAttribute(c,me.TMX_TAG_HEIGHT);this.z=e;a=c.getElementsByTagName(me.TMX_TAG_OBJECT);for(c=0;c<a.length;c++)this.objects.push(new TMXOBject(a[c],b,e))},getObjectCount:function(){return this.objects.length},getObjectByIndex:function(a){return this.objects[a]}});TMXOBject=Object.extend({init:function(a,c,b){this.name=
me.XMLParser.getStringAttribute(a,me.TMX_TAG_NAME);this.x=me.XMLParser.getIntAttribute(a,me.TMX_TAG_X);this.y=me.XMLParser.getIntAttribute(a,me.TMX_TAG_Y);this.z=b;(this.gid=me.XMLParser.getIntAttribute(a,me.TMX_TAG_GID,null))?(c=c.getTilesetByGid(this.gid),this.width=c.tilewidth,this.height=c.tileheight,this.spritewidth=this.width,this.y-=this.height,this.image=c.getTileImage(this.gid-c.firstgid)):(this.width=me.XMLParser.getIntAttribute(a,me.TMX_TAG_WIDTH,0),this.height=me.XMLParser.getIntAttribute(a,
me.TMX_TAG_HEIGHT,0));me.TMXUtils.setTMXProperties(this,a)},getObjectPropertyByName:function(a){return this[a]}})})(window);
(function(){me.TMXTilesetGroup=Object.extend({init:function(){this.tilesets=[]},add:function(a){this.tilesets.push(a)},getTilesetByIndex:function(a){return this.tilesets[a]},getTilesetByGid:function(a){for(var c=-1,b=0,e=this.tilesets.length;b<e;b++){if(this.tilesets[b].contains(a))return this.tilesets[b];this.tilesets[b].firstgid==this.tilesets[b].lastgid&&a>=this.tilesets[b].firstgid&&(c=b)}if(-1!=c)return this.tilesets[c];throw"no matching tileset found for gid "+a;}});me.TMXTileset=me.Tileset.extend({init:function(a){this.firstgid=
me.XMLParser.getIntAttribute(a,me.TMX_TAG_FIRSTGID);this.parent(me.XMLParser.getStringAttribute(a,me.TMX_TAG_NAME),me.XMLParser.getIntAttribute(a,me.TMX_TAG_TILEWIDTH),me.XMLParser.getIntAttribute(a,me.TMX_TAG_TILEHEIGHT),me.XMLParser.getIntAttribute(a,me.TMX_TAG_SPACING,0),me.XMLParser.getIntAttribute(a,me.TMX_TAG_MARGIN,0),a.getElementsByTagName(me.TMX_TAG_IMAGE)[0].getAttribute(me.TMX_TAG_SOURCE));this.lastgid=this.firstgid+(this.hTileCount*this.vTileCount-1||0);this.trans=a.getElementsByTagName(me.TMX_TAG_IMAGE)[0].getAttribute(me.TMX_TAG_TRANS);
if(null!==this.trans&&this.image)this.image=me.video.applyRGBFilter(this.image,"transparent",this.trans.toUpperCase()).canvas;this.tileoffset=new me.Vector2d(0,0);var c=a.getElementsByTagName(me.TMX_TAG_TILEOFFSET);if(0<c.length)this.tileoffset.x=me.XMLParser.getIntAttribute(c[0],me.TMX_TAG_X),this.tileoffset.y=me.XMLParser.getIntAttribute(c[0],me.TMX_TAG_Y);a=a.getElementsByTagName(me.TMX_TAG_TILE);for(c=0;c<a.length;c++){var b=me.XMLParser.getIntAttribute(a[c],me.TMX_TAG_ID)+this.firstgid;this.TileProperties[b]=
{};b=this.TileProperties[b];me.TMXUtils.setTMXProperties(b,a[c]);b.isSolid=b.type?b.type.toLowerCase()===this.type.SOLID:!1;b.isPlatform=b.type?b.type.toLowerCase()===this.type.PLATFORM:!1;b.isLeftSlope=b.type?b.type.toLowerCase()===this.type.L_SLOPE:!1;b.isRightSlope=b.type?b.type.toLowerCase()===this.type.R_SLOPE:!1;b.isBreakable=b.type?b.type.toLowerCase()===this.type.BREAKABLE:!1;b.isLadder=b.type?b.type.toLowerCase()===this.type.LADDER:!1;b.isSlope=b.isLeftSlope||b.isRightSlope;b.isCollidable=
b.isSolid||b.isPlatform||b.isSlope||b.isLadder||b.isBreakable}},contains:function(a){return a>=this.firstgid&&a<=this.lastgid}})})(window);
(function(){TMXRenderer=Object.extend({init:function(a,c,b,e,d){this.predraw=a;this.width=c;this.height=b;this.tilewidth=e;this.tileheight=d},drawTile:function(){}});me.TMXOrthogonalRenderer=TMXRenderer.extend({drawTile:function(a,c,b,e,d,f,g,j){d.drawTile(a,d.tileoffset.x+c*this.tilewidth,d.tileoffset.y+(b+1)*this.tileheight-d.tileheight,e-d.firstgid,f,g,j)}});me.TMXIsometricRenderer=TMXRenderer.extend({drawTile:function(a,c,b,e,d,f,g,j){d.drawTile(a,(this.width-1)*d.tilewidth+(c-b)*d.tilewidth>>
1,-d.tilewidth+(c+b)*d.tileheight>>2,e-d.firstgid,f,g,j)}})})(window);
(function(){me.TMXTileMap=me.TileMap.extend({init:function(a,c,b){this.parent(c,b);this.xmlMap=me.loader.getXML(a);if(!this.xmlMap)throw"melonJS:"+a+" TMX map not found";this.orientation=this.version="";this.tilesets=this.tileMapCanvas=null},load:function(){if(!this.initialized){var a=0,c=1;me.XMLParser.parseFromString(this.xmlMap);for(var b=me.XMLParser.getAllTagElements(),e=0;e<b.length;e++)switch(b.item(e).nodeName){case me.TMX_TAG_MAP:var d=b.item(e);this.version=me.XMLParser.getStringAttribute(d,
me.TMX_TAG_VERSION);this.orientation=me.XMLParser.getStringAttribute(d,me.TMX_TAG_ORIENTATION);this.width=me.XMLParser.getIntAttribute(d,me.TMX_TAG_WIDTH);this.height=me.XMLParser.getIntAttribute(d,me.TMX_TAG_HEIGHT);this.tilewidth=me.XMLParser.getIntAttribute(d,me.TMX_TAG_TILEWIDTH);this.tileheight=me.XMLParser.getIntAttribute(d,me.TMX_TAG_TILEHEIGHT);this.realwidth=this.width*this.tilewidth;this.realheight=this.height*this.tileheight;this.z=a++;me.TMXUtils.setTMXProperties(this,d);this.visible=
!1;if(this.background_color)this.visible=!0,this.background_color=me.utils.HexToRGB(this.background_color);if(this.background_image)this.visible=!0,this.background_image=me.loader.getImage(this.background_image);break;case me.TMX_TAG_TILESET:if(!this.tilesets)this.tilesets=new me.TMXTilesetGroup;this.tilesets.add(new me.TMXTileset(b.item(e)));break;case me.TMX_TAG_LAYER:if(me.XMLParser.getStringAttribute(b.item(e),me.TMX_TAG_NAME).toLowerCase().contains(me.LevelConstants.PARALLAX_MAP)){if(1==me.XMLParser.getIntAttribute(b.item(e),
me.TMX_TAG_VISIBLE,1)){d={};me.TMXUtils.setTMXProperties(d,b.item(e));var f=this.getLayerByName(me.LevelConstants.PARALLAX_MAP);f||(f=new me.ParallaxBackgroundEntity(a),this.mapLayers.push(f));f.addLayer(d.imagesrc,c++,a++)}}else this.mapLayers.push(new me.TMXLayer(b.item(e),this.tilewidth,this.tileheight,this.orientation,this.tilesets,a++)),a++;break;case me.TMX_TAG_OBJECTGROUP:d=me.XMLParser.getStringAttribute(b.item(e),me.TMX_TAG_NAME),this.objectGroups.push(new me.TMXOBjectGroup(d,b.item(e),this.tilesets,
a++))}me.XMLParser.free();this.initialized=!0}},draw:function(a,c){if(this.background_color)a.fillStyle=this.background_color,a.fillRect(c.left,c.top,c.width,c.height);this.background_image&&a.drawImage(this.background_image,c.left,c.top,c.width,c.height,c.left,c.top,c.width,c.height)}});me.TMXLayer=me.TiledLayer.extend({init:function(a,c,b,e,d,f){this.parent(me.XMLParser.getIntAttribute(a,me.TMX_TAG_WIDTH),me.XMLParser.getIntAttribute(a,me.TMX_TAG_HEIGHT),c,b,d,f);this.orientation=e;this.layerInvalidated=
!0;this.name=me.XMLParser.getStringAttribute(a,me.TMX_TAG_NAME);this.visible=1==me.XMLParser.getIntAttribute(a,me.TMX_TAG_VISIBLE,1);this.opacity=me.XMLParser.getFloatAttribute(a,me.TMX_TAG_OPACITY,1);me.TMXUtils.setTMXProperties(this,a);if(this.isCollisionMap=this.name.toLowerCase().contains(me.LevelConstants.COLLISION_MAP))this.visible=!1;this.vp=me.game.viewport;a=a.getElementsByTagName(me.TMX_TAG_DATA)[0];c=me.XMLParser.getStringAttribute(a,me.TMX_TAG_ENCODING,null);b=me.XMLParser.getStringAttribute(a,
me.TMX_TAG_COMPRESSION,null);""==c&&(c=null);""==b&&(b=null);if(this.visible){switch(this.orientation){case "orthogonal":this.renderer=new me.TMXOrthogonalRenderer(!0,this.width,this.height,this.tilewidth,this.tileheight);break;case "isometric":this.renderer=new me.TMXIsometricRenderer(!0,this.width,this.height,this.tilewidth,this.tileheight);break;default:throw"melonJS: "+this.orientation+" type TMX Tile Map not supported!";}this.layerSurface=me.video.createCanvasSurface(this.width*this.tilewidth,
this.height*this.tileheight);this.layerCanvas=this.layerSurface.canvas;if(0<this.opacity&&1>this.opacity)this.layerSurface.globalAlpha=this.opacity}if(this.visible||this.isCollisionMap)this.initArray(this.isCollisionMap),this.fillArray(a,c,b)},fillArray:function(a,c,b){switch(b){case null:switch(c){case null:a=a.getElementsByTagName(me.TMX_TAG_TILE);break;case me.TMX_TAG_CSV:case me.TMX_TAG_ATTR_BASE64:for(var b="",e=0,d=a.childNodes.length;e<d;e++)b+=a.childNodes[e].nodeValue;a=c==me.TMX_TAG_ATTR_BASE64?
me.utils.decodeBase64AsArray(b,4):me.utils.decodeCSV(b,this.width);break;default:throw"melonJS: TMX Tile Map "+c+" encoding not supported!";}break;default:throw"melonJS: "+b+" compressed TMX Tile Map not supported!";}for(var b=0,f,g,j=0;j<this.height;j++)for(var h=0;h<this.width;h++)if(g=null==c?me.XMLParser.getIntAttribute(a[b++],me.TMX_TAG_GID):a[b++],e=g&2147483648,d=g&1073741824,f=g&536870912,g&=536870911,0<g){this.setTile(h,j,g);if(!this.tileset.contains(g))this.tileset=this.tilesets.getTilesetByGid(g);
this.visible&&this.renderer.drawTile(this.layerSurface,h,j,g,this.tileset,e,d,f)}},clearTile:function(a,c){this.parent(a,c);this.visible&&this.layerSurface.clearRect(a*this.tilewidth,c*this.tileheight,this.tilewidth,this.tileheight)},draw:function(a,c){a.drawImage(this.layerCanvas,this.vp.pos.x+c.pos.x,this.vp.pos.y+c.pos.y,c.width,c.height,c.pos.x,c.pos.y,c.width,c.height)}})})(window);
(function(){me.Tween=function(a){var c={},b={},e={},d=1E3,f=0,g=null,j=me.Tween.Easing.Linear.EaseNone,h=null,k=null,l=null;this.to=function(b,c){null!==c&&(d=c);for(var f in b)null!==a[f]&&(e[f]=b[f]);return this};this.start=function(){me.game.add(this,999);g=me.timer.getTime()+f;for(var d in e)null!==a[d]&&(c[d]=a[d],b[d]=e[d]-a[d]);return this};this.stop=function(){me.game.remove(this);return this};this.delay=function(a){f=a;return this};this.easing=function(a){j=a;return this};this.chain=function(a){h=
a;return this};this.onUpdate=function(a){k=a;return this};this.onComplete=function(a){l=a;return this};this.update=function(){var e,f,n;f=me.timer.getTime();if(f<g)return!0;f=(f-g)/d;f=1<f?1:f;n=j(f);for(e in b)a[e]=c[e]+b[e]*n;null!==k&&k.call(a,n);return 1==f?(me.game.remove(this),null!==l&&l.call(a),null!==h&&h.start(),!1):!0};this.destroy=function(){return!0}};me.Tween.Easing={Linear:{},Quadratic:{},Cubic:{},Quartic:{},Quintic:{},Sinusoidal:{},Exponential:{},Circular:{},Elastic:{},Back:{},Bounce:{}};
me.Tween.Easing.Linear.EaseNone=function(a){return a};me.Tween.Easing.Quadratic.EaseIn=function(a){return a*a};me.Tween.Easing.Quadratic.EaseOut=function(a){return-a*(a-2)};me.Tween.Easing.Quadratic.EaseInOut=function(a){return 1>(a*=2)?0.5*a*a:-0.5*(--a*(a-2)-1)};me.Tween.Easing.Cubic.EaseIn=function(a){return a*a*a};me.Tween.Easing.Cubic.EaseOut=function(a){return--a*a*a+1};me.Tween.Easing.Cubic.EaseInOut=function(a){return 1>(a*=2)?0.5*a*a*a:0.5*((a-=2)*a*a+2)};me.Tween.Easing.Quartic.EaseIn=function(a){return a*
a*a*a};me.Tween.Easing.Quartic.EaseOut=function(a){return-(--a*a*a*a-1)};me.Tween.Easing.Quartic.EaseInOut=function(a){return 1>(a*=2)?0.5*a*a*a*a:-0.5*((a-=2)*a*a*a-2)};me.Tween.Easing.Quintic.EaseIn=function(a){return a*a*a*a*a};me.Tween.Easing.Quintic.EaseOut=function(a){return(a-=1)*a*a*a*a+1};me.Tween.Easing.Quintic.EaseInOut=function(a){return 1>(a*=2)?0.5*a*a*a*a*a:0.5*((a-=2)*a*a*a*a+2)};me.Tween.Easing.Sinusoidal.EaseIn=function(a){return-Math.cos(a*Math.PI/2)+1};me.Tween.Easing.Sinusoidal.EaseOut=
function(a){return Math.sin(a*Math.PI/2)};me.Tween.Easing.Sinusoidal.EaseInOut=function(a){return-0.5*(Math.cos(Math.PI*a)-1)};me.Tween.Easing.Exponential.EaseIn=function(a){return 0==a?0:Math.pow(2,10*(a-1))};me.Tween.Easing.Exponential.EaseOut=function(a){return 1==a?1:-Math.pow(2,-10*a)+1};me.Tween.Easing.Exponential.EaseInOut=function(a){return 0==a?0:1==a?1:1>(a*=2)?0.5*Math.pow(2,10*(a-1)):0.5*(-Math.pow(2,-10*(a-1))+2)};me.Tween.Easing.Circular.EaseIn=function(a){return-(Math.sqrt(1-a*a)-1)};
me.Tween.Easing.Circular.EaseOut=function(a){return Math.sqrt(1- --a*a)};me.Tween.Easing.Circular.EaseInOut=function(a){return 1>(a/=0.5)?-0.5*(Math.sqrt(1-a*a)-1):0.5*(Math.sqrt(1-(a-=2)*a)+1)};me.Tween.Easing.Elastic.EaseIn=function(a){var c,b=0.1,e=0.4;if(0==a)return 0;if(1==a)return 1;e||(e=0.3);!b||1>b?(b=1,c=e/4):c=e/(2*Math.PI)*Math.asin(1/b);return-(b*Math.pow(2,10*(a-=1))*Math.sin((a-c)*2*Math.PI/e))};me.Tween.Easing.Elastic.EaseOut=function(a){var c,b=0.1,e=0.4;if(0==a)return 0;if(1==a)return 1;
e||(e=0.3);!b||1>b?(b=1,c=e/4):c=e/(2*Math.PI)*Math.asin(1/b);return b*Math.pow(2,-10*a)*Math.sin((a-c)*2*Math.PI/e)+1};me.Tween.Easing.Elastic.EaseInOut=function(a){var c,b=0.1,e=0.4;if(0==a)return 0;if(1==a)return 1;e||(e=0.3);!b||1>b?(b=1,c=e/4):c=e/(2*Math.PI)*Math.asin(1/b);return 1>(a*=2)?-0.5*b*Math.pow(2,10*(a-=1))*Math.sin((a-c)*2*Math.PI/e):0.5*b*Math.pow(2,-10*(a-=1))*Math.sin((a-c)*2*Math.PI/e)+1};me.Tween.Easing.Back.EaseIn=function(a){return a*a*(2.70158*a-1.70158)};me.Tween.Easing.Back.EaseOut=
function(a){return(a-=1)*a*(2.70158*a+1.70158)+1};me.Tween.Easing.Back.EaseInOut=function(a){return 1>(a*=2)?0.5*a*a*(3.5949095*a-2.5949095):0.5*((a-=2)*a*(3.5949095*a+2.5949095)+2)};me.Tween.Easing.Bounce.EaseIn=function(a){return 1-Tween.Easing.Bounce.EaseOut(1-a)};me.Tween.Easing.Bounce.EaseOut=function(a){return(a/=1)<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:7.5625*(a-=2.625/2.75)*a+0.984375};me.Tween.Easing.Bounce.EaseInOut=function(a){return 0.5>
a?0.5*Tween.Easing.Bounce.EaseIn(2*a):0.5*Tween.Easing.Bounce.EaseOut(2*a-1)+0.5}})(window);
