import { describe, expect, it, vi } from "vitest";
import { GLShader, ShaderEffect } from "../src/index.js";
import { compileShaderAsset } from "../src/loader/parsers/shader.js";
import { emit, VIDEO_INIT } from "../src/system/event.ts";

/**
 * compileShaderAsset dispatch on a non-WebGL renderer — pinned against a
 * stub (this path only reads `renderer.gl` for programs and
 * `shaderLanguage` for effect bodies), in its own spec file: emitting
 * VIDEO_INIT swaps the parser's captured renderer for the rest of this
 * module registry, so nothing else may share the file.
 */

const WGSL_MODULE = [
	"@vertex",
	"fn vertex_main(@location(0) aVertex : vec3f) -> @builtin(position) vec4f {",
	"    return vec4f(aVertex, 1.0);",
	"}",
	"@fragment",
	"fn fragment_main() -> @location(0) vec4f {",
	"    return vec4f(1.0);",
	"}",
].join("\n");

// an effect BODY (the apply() convention) — no @vertex entry point, so the
// module sniff must route it to ShaderEffect, not a raw program
const WGSL_BODY = [
	"struct Fx { uIntensity : f32, };",
	"@group(3) @binding(0) var<uniform> fx : Fx;",
	"fn apply(color : vec4f, uv : vec2f) -> vec4f {",
	"    return mix(color, vec4f(1.0), fx.uIntensity);",
	"}",
].join("\n");

const PAIR = {
	vertex:
		"attribute vec3 aVertex; void main(void) { gl_Position = vec4(aVertex, 1.0); }",
	fragment: "void main(void) { gl_FragColor = vec4(1.0); }",
};

describe("compileShaderAsset on a WGSL renderer (stub, no gl)", () => {
	emit(VIDEO_INIT, { shaderLanguage: "wgsl" });

	it("a complete dual-backend program compiles into one shared GLShader carrying the module", () => {
		const shader = compileShaderAsset({ ...PAIR, wgsl: WGSL_MODULE });
		expect(shader).toBeInstanceOf(GLShader);
		expect(shader.shared).toBe(true);
		expect(shader.wgsl).toBe(WGSL_MODULE);
		expect(shader.isWebGPU).toBe(true);
		// no GL context on this renderer — the GLSL pair is carried, not compiled
		expect(shader.isWebGL).toBe(false);
	});

	it("a wgsl-module-only source works too — no GLSL pair required", () => {
		const shader = compileShaderAsset({ wgsl: WGSL_MODULE });
		expect(shader).toBeInstanceOf(GLShader);
		expect(shader.isWebGPU).toBe(true);
	});

	it("a GLSL-only program pair loads as an inert shader with one warning", () => {
		const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
		const shader = compileShaderAsset(PAIR);
		expect(shader).toBeInstanceOf(GLShader);
		expect(shader.isWebGL).toBe(false);
		expect(shader.isWebGPU).toBe(false);
		expect(shader.shared).toBe(true);
		expect(warn).toHaveBeenCalledTimes(1);
		expect(warn.mock.calls[0][0]).toMatch(/realization/);
		warn.mockRestore();
	});

	it("a wgsl effect BODY (no @vertex) still routes to ShaderEffect", () => {
		const fx = compileShaderAsset({ wgsl: WGSL_BODY });
		expect(fx).toBeInstanceOf(ShaderEffect);
		expect(fx.shared).toBe(true);
	});

	it("an effect body that merely MENTIONS @vertex in a comment is not misrouted", () => {
		const commented = [
			"// note: the @vertex stage is generated by the realization",
			"/* likewise a block comment naming @vertex and fn vertex_main */",
			WGSL_BODY,
		].join("\n");
		const fx = compileShaderAsset({ wgsl: commented });
		expect(fx).toBeInstanceOf(ShaderEffect);
	});

	it("a module needs BOTH @vertex and the vertex_main entry point", () => {
		// @vertex over a differently-named entry point is not the hosted
		// mesh contract — treated as a body (and would fail realization,
		// surfacing the actual authoring error instead of a silent misroute)
		const wrongEntry = WGSL_MODULE.replace(/vertex_main/g, "customMain");
		expect(compileShaderAsset({ wgsl: wrongEntry })).toBeInstanceOf(
			ShaderEffect,
		);
	});
});

describe("compileShaderAsset without a programmable pipeline (stub)", () => {
	it("program assets still load — inert when nothing can be hosted", () => {
		emit(VIDEO_INIT, { shaderLanguage: null });
		const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
		// with a wgsl module declared, the shader carries a realization
		// (harmlessly unused on Canvas) — no warning
		const dual = compileShaderAsset({ ...PAIR, wgsl: WGSL_MODULE });
		expect(dual).toBeInstanceOf(GLShader);
		expect(warn).not.toHaveBeenCalled();
		// pair-only: nothing hostable anywhere — warn once, stay inert
		const inert = compileShaderAsset(PAIR);
		expect(inert).toBeInstanceOf(GLShader);
		expect(inert.isWebGL).toBe(false);
		expect(inert.isWebGPU).toBe(false);
		expect(warn).toHaveBeenCalledTimes(1);
		warn.mockRestore();
	});
});
